### ISSUE TITLE
Répétitions au niveau du CSS

### ISSUE THREAD

**Issue by Pauline-Bonnet** [KiruaZoldic/my-card#4]
Tu as des éléments qui se répètent dans ton CSS. Dans ces cas-là, tu peux les factoriser, afin de limiter au maximum la répétition (en dev, on aime économiser des lignes de code)
Donc tu as : .main-title, .description-title, .bio-title, .cda-quote qui ont la même font-family
Tu pourrais écrire : 
```css
.main-title, .description-title, .bio-title, .cda-quote {
     font-family: "Playwrite FR Moderne", sans-serif;
}

.description-title, .bio-title {
     font-size: clamp(1.15rem, 2.5vw, 1.25rem);
     text-transform: uppercase;
     margin-bottom: 1rem;
}
``` 

Le fait de mettre deux sélecteurs css (typiquement ici deux noms de classes), séparés par une virgule, ça fait que tu listes les noms de classes qui auront des propriétés en commun. Donc si tu as besoin de règles spécifiques, tu pourras faire comme d'habitude
